/**
 * Copyright 2026 ResQ
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

namespace ResQ.Blockchain;

/// <summary>
/// Represents the result of a blockchain transaction submission.
/// </summary>
/// <remarks>
/// This record contains all relevant information about a transaction after it has been
/// submitted to the Neo N3 blockchain, including its hash, confirmation status, and
/// the block height at which it was included.
/// </remarks>
/// <param name="TransactionHash">The hexadecimal hash of the transaction.</param>
/// <param name="IsConfirmed">True if the transaction has been confirmed on-chain.</param>
/// <param name="BlockHeight">The block number where the transaction was included.</param>
/// <param name="Timestamp">The UTC timestamp when the result was created.</param>
/// <example>
/// <code>
/// var result = new TransactionResult(
///     TransactionHash: "0xabc123...",
///     IsConfirmed: true,
///     BlockHeight: 1234567,
///     Timestamp: DateTimeOffset.UtcNow
/// );
/// 
/// if (result.IsConfirmed)
/// {
///     Console.WriteLine($"Confirmed in block {result.BlockHeight}");
/// }
/// </code>
/// </example>
public record TransactionResult(
    string TransactionHash,
    bool IsConfirmed,
    ulong BlockHeight,
    DateTimeOffset Timestamp
);

/// <summary>
/// Represents an event to be recorded on the blockchain for immutable logging.
/// </summary>
/// <remarks>
/// Blockchain events provide an immutable audit trail of critical system activities.
/// Each event is assigned a unique ID and can optionally reference IPFS content
/// for additional evidence storage.
/// </remarks>
/// <param name="EventId">Unique identifier for this event.</param>
/// <param name="EventType">The type/category of the event.</param>
/// <param name="Payload">JSON payload containing event-specific data.</param>
/// <param name="IpfsCid">Optional IPFS Content Identifier for associated evidence.</param>
/// <param name="Timestamp">UTC timestamp when the event occurred.</param>
/// <example>
/// <code>
/// var evt = new BlockchainEvent(
///     EventId: "evt-001",
///     EventType: "IncidentDetected",
///     Payload: "{\"incidentId\":\"inc-001\",\"severity\":\"High\"}",
///     IpfsCid: "Qmabc123...",
///     Timestamp: DateTimeOffset.UtcNow
/// );
/// 
/// var result = await neoClient.RecordEventAsync(evt);
/// </code>
/// </example>
public record BlockchainEvent(
    string EventId,
    string EventType,
    string Payload,
    string? IpfsCid,
    DateTimeOffset Timestamp
);

/// <summary>
/// Represents a cryptographically signed location attestation for a drone.
/// </summary>
/// <remarks>
/// Location attestations provide verifiable proof of a drone's position at a specific
/// time. The signature allows verification that the location data was generated by
/// the legitimate drone and has not been tampered with.
/// </remarks>
/// <param name="DroneId">Unique identifier of the drone.</param>
/// <param name="Latitude">Latitude in decimal degrees (-90 to 90).</param>
/// <param name="Longitude">Longitude in decimal degrees (-180 to 180).</param>
/// <param name="Altitude">Altitude in meters above sea level.</param>
/// <param name="Timestamp">UTC timestamp of the attestation.</param>
/// <param name="Signature">Cryptographic signature verifying the attestation.</param>
/// <example>
/// <code>
/// var attestation = new LocationAttestation(
///     DroneId: "drn-001",
///     Latitude: 37.7749,
///     Longitude: -122.4194,
///     Altitude: 100.5,
///     Timestamp: DateTimeOffset.UtcNow,
///     Signature: "0x..."
/// );
/// 
/// var isValid = await neoClient.VerifyLocationAttestationAsync(attestation);
/// </code>
/// </example>
public record LocationAttestation(
    string DroneId,
    double Latitude,
    double Longitude,
    double Altitude,
    DateTimeOffset Timestamp,
    string Signature
);

/// <summary>
/// Represents evidence metadata linked to IPFS storage.
/// </summary>
/// <remarks>
/// Evidence records link incidents to their associated evidence stored on IPFS.
/// The hash field provides a content verification mechanism to ensure evidence
/// integrity when retrieved from IPFS.
/// </remarks>
/// <param name="IncidentId">ID of the incident this evidence belongs to.</param>
/// <param name="IpfsCid">IPFS Content Identifier for the evidence file.</param>
/// <param name="ContentType">MIME type of the evidence (e.g., "image/jpeg", "video/mp4").</param>
/// <param name="SizeBytes">Size of the evidence file in bytes.</param>
/// <param name="Hash">Cryptographic hash of the evidence content for verification.</param>
/// <example>
/// <code>
/// var evidence = new EvidenceRecord(
///     IncidentId: "inc-001",
///     IpfsCid: "Qmabc123...",
///     ContentType: "image/jpeg",
///     SizeBytes: 1024567,
///     Hash: "sha256:..."
/// );
/// 
/// var result = await neoClient.RecordEvidenceAsync(evidence);
/// </code>
/// </example>
public record EvidenceRecord(
    string IncidentId,
    string IpfsCid,
    string ContentType,
    long SizeBytes,
    string Hash
);

/// <summary>
/// Interface for Neo N3 blockchain operations.
/// </summary>
/// <remarks>
/// This interface defines the contract for interacting with the Neo N3 blockchain.
/// Implementations provide methods for recording events, verifying attestations,
/// and querying blockchain state. Use <see cref="MockNeoClient"/> for testing
/// and development without a real blockchain connection.
/// </remarks>
/// <example>
/// <code>
/// // Dependency injection registration
/// services.AddSingleton&lt;INeoClient, MockNeoClient&gt;();
/// 
/// // Usage
/// public class IncidentService
/// {
///     private readonly INeoClient _neoClient;
///     
///     public IncidentService(INeoClient neoClient)
///     {
///         _neoClient = neoClient;
///     }
///     
///     public async Task RecordIncidentAsync(BlockchainEvent evt)
///     {
///         var result = await _neoClient.RecordEventAsync(evt);
///         if (result.IsConfirmed)
///         {
///             Console.WriteLine($"Recorded: {result.TransactionHash}");
///         }
///     }
/// }
/// </code>
/// </example>
public interface INeoClient
{
    /// <summary>
    /// Records an event on the Neo N3 blockchain.
    /// </summary>
    /// <param name="evt">The blockchain event to record.</param>
    /// <param name="cancellationToken">Cancellation token for the operation.</param>
    /// <returns>
    /// A <see cref="TransactionResult"/> containing the transaction hash and confirmation status.
    /// </returns>
    /// <exception cref="InvalidOperationException">Thrown when the blockchain operation fails.</exception>
    /// <exception cref="OperationCanceledException">Thrown when the operation is cancelled.</exception>
    /// <remarks>
    /// Events are permanently recorded on the blockchain and provide an immutable audit trail.
    /// The operation may take several seconds to complete as it waits for transaction confirmation.
    /// </remarks>
    /// <example>
    /// <code>
    /// var evt = new BlockchainEvent(
    ///     EventId: "evt-001",
    ///     EventType: "IncidentDetected",
    ///     Payload: "{\"id\":\"inc-001\"}",
    ///     IpfsCid: null,
    ///     Timestamp: DateTimeOffset.UtcNow
    /// );
    /// 
    /// var result = await neoClient.RecordEventAsync(evt);
    /// Console.WriteLine($"Transaction: {result.TransactionHash}");
    /// </code>
    /// </example>
    Task<TransactionResult> RecordEventAsync(
        BlockchainEvent evt,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Records a drone location attestation on the blockchain.
    /// </summary>
    /// <param name="attestation">The location attestation containing drone position and signature.</param>
    /// <param name="cancellationToken">Cancellation token for the operation.</param>
    /// <returns>
    /// A <see cref="TransactionResult"/> containing the transaction hash and confirmation status.
    /// </returns>
    /// <exception cref="InvalidOperationException">Thrown when the blockchain operation fails.</exception>
    /// <exception cref="OperationCanceledException">Thrown when the operation is cancelled.</exception>
    /// <remarks>
    /// Location attestations provide cryptographic proof of a drone's position at a specific time.
    /// This is useful for compliance, incident reconstruction, and verification of mission execution.
    /// </remarks>
    /// <example>
    /// <code>
    /// var attestation = new LocationAttestation(
    ///     DroneId: "drn-001",
    ///     Latitude: 37.7749,
    ///     Longitude: -122.4194,
    ///     Altitude: 100.0,
    ///     Timestamp: DateTimeOffset.UtcNow,
    ///     Signature: "0x..."
    /// );
    /// 
    /// var result = await neoClient.RecordLocationAttestationAsync(attestation);
    /// </code>
    /// </example>
    Task<TransactionResult> RecordLocationAttestationAsync(
        LocationAttestation attestation,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Verifies a location attestation signature on the blockchain.
    /// </summary>
    /// <param name="attestation">The location attestation to verify.</param>
    /// <param name="cancellationToken">Cancellation token for the operation.</param>
    /// <returns>
    /// True if the attestation signature is valid and matches the drone's registered public key;
    /// false otherwise.
    /// </returns>
    /// <exception cref="OperationCanceledException">Thrown when the operation is cancelled.</exception>
    /// <remarks>
    /// This method verifies that the location data was signed by the legitimate drone
    /// and has not been tampered with. It checks the signature against the drone's
    /// public key stored on the blockchain.
    /// </remarks>
    /// <example>
    /// <code>
    /// var isValid = await neoClient.VerifyLocationAttestationAsync(attestation);
    /// if (isValid)
    /// {
    ///     Console.WriteLine("Location attestation verified");
    /// }
    /// else
    /// {
    ///     Console.WriteLine("WARNING: Invalid attestation signature!");
    /// }
    /// </code>
    /// </example>
    Task<bool> VerifyLocationAttestationAsync(
        LocationAttestation attestation,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Records evidence metadata on the blockchain with a reference to IPFS storage.
    /// </summary>
    /// <param name="evidence">The evidence record containing IPFS CID and metadata.</param>
    /// <param name="cancellationToken">Cancellation token for the operation.</param>
    /// <returns>
    /// A <see cref="TransactionResult"/> containing the transaction hash and confirmation status.
    /// </returns>
    /// <exception cref="InvalidOperationException">Thrown when the blockchain operation fails.</exception>
    /// <exception cref="OperationCanceledException">Thrown when the operation is cancelled.</exception>
    /// <remarks>
    /// Evidence is stored on IPFS for decentralized storage, while the blockchain records
    /// a permanent, immutable reference to the evidence along with its hash for integrity verification.
    /// </remarks>
    /// <example>
    /// <code>
    /// var evidence = new EvidenceRecord(
    ///     IncidentId: "inc-001",
    ///     IpfsCid: "Qmabc123...",
    ///     ContentType: "image/jpeg",
    ///     SizeBytes: 1024567,
    ///     Hash: "sha256:..."
    /// );
    /// 
    /// var result = await neoClient.RecordEvidenceAsync(evidence);
    /// Console.WriteLine($"Evidence recorded: {result.TransactionHash}");
    /// </code>
    /// </example>
    Task<TransactionResult> RecordEvidenceAsync(
        EvidenceRecord evidence,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Retrieves all blockchain events associated with a specific incident.
    /// </summary>
    /// <param name="incidentId">The unique identifier of the incident.</param>
    /// <param name="cancellationToken">Cancellation token for the operation.</param>
    /// <returns>
    /// A read-only list of <see cref="BlockchainEvent"/> records associated with the incident.
    /// Returns an empty list if no events are found.
    /// </returns>
    /// <exception cref="OperationCanceledException">Thrown when the operation is cancelled.</exception>
    /// <remarks>
    /// This method queries the blockchain for all events that reference the specified incident.
    /// Events are returned in chronological order based on their block height.
    /// </remarks>
    /// <example>
    /// <code>
    /// var events = await neoClient.GetEventsByIncidentAsync("inc-001");
    /// foreach (var evt in events)
    /// {
    ///     Console.WriteLine($"{evt.Timestamp}: {evt.EventType}");
    /// }
    /// </code>
    /// </example>
    Task<IReadOnlyList<BlockchainEvent>> GetEventsByIncidentAsync(
        string incidentId,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets the current block height of the blockchain.
    /// </summary>
    /// <param name="cancellationToken">Cancellation token for the operation.</param>
    /// <returns>The current block height as an unsigned 64-bit integer.</returns>
    /// <exception cref="OperationCanceledException">Thrown when the operation is cancelled.</exception>
    /// <remarks>
    /// The block height represents the number of blocks in the blockchain and increases
    /// approximately every 15 seconds on Neo N3. This can be used to estimate confirmation
    /// times and determine if transactions have been finalized.
    /// </remarks>
    /// <example>
    /// <code>
    /// var height = await neoClient.GetBlockHeightAsync();
    /// Console.WriteLine($"Current block: {height}");
    /// 
    /// // Check if a transaction is confirmed (6+ blocks)
    /// var txBlockHeight = result.BlockHeight;
    /// if (height - txBlockHeight >= 6)
    /// {
    ///     Console.WriteLine("Transaction is finalized");
    /// }
    /// </code>
    /// </example>
    Task<ulong> GetBlockHeightAsync(CancellationToken cancellationToken = default);
}
