/**
 * Copyright 2026 ResQ
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System.Buffers.Binary;

namespace ResQ.Mavlink.Messages;

/// <summary>
/// MAVLink RADIO_STATUS message (ID 109). Status generated by radio and injected into MAVLink stream.
/// </summary>
public readonly record struct RadioStatus : IMavlinkMessage
{
    /// <summary>Payload size in bytes.</summary>
    public const int PayloadSize = 9;

    /// <summary>Count of radio packet receive errors.</summary>
    public ushort Rxerrors { get; init; }

    /// <summary>Count of error-corrected radio packets.</summary>
    public ushort Fixed { get; init; }

    /// <summary>Local (message receiver) recieved signal strength indication in dBm.</summary>
    public byte Rssi { get; init; }

    /// <summary>Remote (message sender) signal strength indication in dBm.</summary>
    public byte Remrssi { get; init; }

    /// <summary>Remaining free transmitter buffer space.</summary>
    public byte Txbuf { get; init; }

    /// <summary>Local background noise level in dBm.</summary>
    public byte Noise { get; init; }

    /// <summary>Remote background noise level in dBm.</summary>
    public byte Remnoise { get; init; }

    /// <inheritdoc/>
    public uint MessageId => 109;

    /// <inheritdoc/>
    public byte CrcExtra => 185;

    /// <inheritdoc/>
    public void Serialize(Span<byte> buffer)
    {
        BinaryPrimitives.WriteUInt16LittleEndian(buffer, Rxerrors);
        BinaryPrimitives.WriteUInt16LittleEndian(buffer[2..], Fixed);
        buffer[4] = Rssi;
        buffer[5] = Remrssi;
        buffer[6] = Txbuf;
        buffer[7] = Noise;
        buffer[8] = Remnoise;
    }

    /// <summary>Deserializes a <see cref="RadioStatus"/> from a raw payload span.</summary>
    public static RadioStatus Deserialize(ReadOnlySpan<byte> buffer) =>
        new()
        {
            Rxerrors = BinaryPrimitives.ReadUInt16LittleEndian(buffer),
            Fixed = BinaryPrimitives.ReadUInt16LittleEndian(buffer[2..]),
            Rssi = buffer[4],
            Remrssi = buffer[5],
            Txbuf = buffer[6],
            Noise = buffer[7],
            Remnoise = buffer[8],
        };
}
